[package]
name = "cargo-scout"
version = "0.1.0"
authors = ["Jeremy Lempereur <jeremy.lempereur@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.10.0"
clap = "2.33.0"
